# Generated by Django 5.2.7 on 2025-12-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='patient_name',
            new_name='tient_name',
        ),
    ]
