# Generated by Django 5.2.7 on 2025-12-17 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_rename_patient_name_bloodrequest_tient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='tient_name',
            new_name='patient_name',
        ),
    ]
