# Generated by Django 5.2.7 on 2025-12-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_donor_last_donation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='needed_date',
            field=models.DateField(null=True),
        ),
    ]
